package com.hackerboard.voice
 
 import android.content.Context
 import android.content.Intent
 import android.os.Bundle
 import android.speech.RecognitionListener
 import android.speech.RecognizerIntent
 import android.speech.SpeechRecognizer
  
  class VoiceInputManager(private val context: Context) {
   
       private var recognizer: SpeechRecognizer? = null
           private var onResult: ((String) -> Unit)? = null
               private var onError: ((String) -> Unit)? = null
                   private var onStateChange: ((Boolean) -> Unit)? = null
                    
                        val isAvailable: Boolean
                                get() = SpeechRecognizer.isRecognitionAvailable(context)
                                 
                                     fun start(
                                             onResult: (String) -> Unit,
                                                     onError: (String) -> Unit = {},
                                                             onStateChange: (Boolean) -> Unit = {},
                                                                 ) {
                                                                         this.onResult      = onResult
                                                                                 this.onError       = onError
                                                                                         this.onStateChange = onStateChange
                                                                                          
                                                                                                  recognizer?.destroy()
                                                                                                          recognizer = SpeechRecognizer.createSpeechRecognizer(context).apply {
                                                                                                                      setRecognitionListener(listener)
                                                                                                                              }
                                                                                                                               
                                                                                                                                       val intent = Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply {
                                                                                                                                                   putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL, RecognizerIntent.LANGUAGE_MODEL_FREE_FORM)
                                                                                                                                                               putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS, true)
                                                                                                                                                                           putExtra(RecognizerIntent.EXTRA_MAX_RESULTS, 1)
                                                                                                                                                                                   }
                                                                                                                                                                                    
                                                                                                                                                                                            recognizer?.startListening(intent)
                                                                                                                                                                                                    onStateChange(true)
                                                                                                                                                                                                        }
                                                                                                                                                                                                         
                                                                                                                                                                                                             fun stop() {
                                                                                                                                                                                                                     recognizer?.stopListening()
                                                                                                                                                                                                                             recognizer?.destroy()
                                                                                                                                                                                                                                     recognizer = null
                                                                                                                                                                                                                                             onStateChange?.invoke(false)
                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                      private val listener = object : RecognitionListener {
                                                                                                                                                                                                                                                              override fun onReadyForSpeech(params: Bundle?) {}
                                                                                                                                                                                                                                                                      override fun onBeginningOfSpeech() {}
                                                                                                                                                                                                                                                                              override fun onRmsChanged(rmsdB: Float) {}
                                                                                                                                                                                                                                                                                      override fun onBufferReceived(buffer: ByteArray?) {}
                                                                                                                                                                                                                                                                                              override fun onEndOfSpeech() { onStateChange?.invoke(false) }
                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                       override fun onResults(results: Bundle?) {
                                                                                                                                                                                                                                                                                                                   val text = results
                                                                                                                                                                                                                                                                                                                                   ?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)
                                                                                                                                                                                                                                                                                                                                                   ?.firstOrNull() ?: return
                                                                                                                                                                                                                                                                                                                                                               onResult?.invoke(text)
                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                override fun onPartialResults(partial: Bundle?) {}
                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                         override fun onError(error: Int) {
                                                                                                                                                                                                                                                                                                                                                                                                     val msg = when (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                     SpeechRecognizer.ERROR_AUDIO             -> "Audio error"
                                                                                                                                                                                                                                                                                                                                                                                                                                     SpeechRecognizer.ERROR_CLIENT            -> "Client error"
                                                                                                                                                                                                                                                                                                                                                                                                                                                     SpeechRecognizer.ERROR_INSUFFICIENT_PERMISSIONS -> "No mic permission"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SpeechRecognizer.ERROR_NETWORK           -> "Network error"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SpeechRecognizer.ERROR_NETWORK_TIMEOUT   -> "Network timeout"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SpeechRecognizer.ERROR_NO_MATCH          -> "No speech detected"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SpeechRecognizer.ERROR_RECOGNIZER_BUSY   -> "Recognizer busy"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SpeechRecognizer.ERROR_SERVER            -> "Server error"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SpeechRecognizer.ERROR_SPEECH_TIMEOUT    -> "Speech timeout"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     else                                     -> "Unknown error"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             onError?.invoke(msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         onStateChange?.invoke(false)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          override fun onEvent(eventType: Int, params: Bundle?) {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   fun destroy() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           recognizer?.destroy()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   recognizer = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }