package com.hackerboard.ui
 
 import androidx.compose.foundation.background
 import androidx.compose.foundation.border
 import androidx.compose.foundation.gestures.detectTapGestures
 import androidx.compose.foundation.layout.*
 import androidx.compose.foundation.shape.RoundedCornerShape
 import androidx.compose.material3.Text
 import androidx.compose.runtime.*
 import androidx.compose.ui.Alignment
 import androidx.compose.ui.Modifier
 import androidx.compose.ui.draw.clip
 import androidx.compose.ui.graphics.Color
 import androidx.compose.ui.input.pointer.pointerInput
 import androidx.compose.ui.text.font.FontFamily
 import androidx.compose.ui.text.font.FontWeight
 import androidx.compose.ui.unit.dp
 import androidx.compose.ui.unit.sp
 import com.hackerboard.keyboard.Key
 import com.hackerboard.keyboard.KeyType
 import com.hackerboard.themes.KeyboardTheme
  
  @Composable
  fun KeyUI(
      key: Key,
          theme: KeyboardTheme,
              isUpperCase: Boolean,
                  isActive: Boolean = false,
                      modifier: Modifier = Modifier,
                          onPress: () -> Unit,
                              onLongPress: (() -> Unit)? = null,
                              ) {
                                  val shape  = RoundedCornerShape(6.dp)
                                      val bgColor = when {
                                              isActive && key.type == KeyType.CTRL  -> theme.accentColor.copy(alpha = 0.25f)
                                                      isActive && key.type == KeyType.SHIFT -> theme.accentColor.copy(alpha = 0.25f)
                                                              key.type == KeyType.ENTER             -> theme.enterKeyBg
                                                                      key.type == KeyType.SPACE             -> theme.spaceKeyBg
                                                                              key.type in listOf(
                                                                                          KeyType.CTRL, KeyType.ALT_KEY, KeyType.SUPER,
                                                                                                      KeyType.ESC,  KeyType.TAB,     KeyType.SHIFT,
                                                                                                                  KeyType.BACKSPACE,
                                                                                                                          )                                     -> theme.specialKeyBg
                                                                                                                                  key.type == KeyType.AI_TOOL ||
                                                                                                                                          key.type == KeyType.VOICE             -> theme.specialKeyBg
                                                                                                                                                  else                                  -> theme.keyBackground
                                                                                                                                                      }
                                                                                                                                                       
                                                                                                                                                           val borderColor = when {
                                                                                                                                                                   isActive -> theme.accentColor.copy(alpha = 0.7f)
                                                                                                                                                                           key.type == KeyType.ENTER -> theme.accentColor.copy(alpha = 0.3f)
                                                                                                                                                                                   else -> theme.keyBorder
                                                                                                                                                                                       }
                                                                                                                                                                                        
                                                                                                                                                                                            Box(
                                                                                                                                                                                                    modifier = modifier
                                                                                                                                                                                                                .clip(shape)
                                                                                                                                                                                                                            .background(bgColor)
                                                                                                                                                                                                                                        .border(0.5.dp, borderColor, shape)
                                                                                                                                                                                                                                                    .pointerInput(key) {
                                                                                                                                                                                                                                                                    detectTapGestures(
                                                                                                                                                                                                                                                                                        onTap      = { onPress() },
                                                                                                                                                                                                                                                                                                            onLongPress = { onLongPress?.invoke() ?: onPress() },
                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                    .padding(horizontal = 1.dp, vertical = 2.dp),
                                                                                                                                                                                                                                                                                                                                                            contentAlignment = Alignment.Center,
                                                                                                                                                                                                                                                                                                                                                                ) {
                                                                                                                                                                                                                                                                                                                                                                        // Top-left alt label
                                                                                                                                                                                                                                                                                                                                                                                if (key.alt.isNotEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                            Text(
                                                                                                                                                                                                                                                                                                                                                                                                            text     = key.alt,
                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize = 7.sp,
                                                                                                                                                                                                                                                                                                                                                                                                                                            color    = theme.keyAltText,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontFamily = FontFamily.Monospace,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modifier = Modifier
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .align(Alignment.TopStart)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .padding(start = 3.dp, top = 2.dp),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Top-right sym label
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (key.sym.isNotEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text     = key.sym,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize = 7.sp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color    = theme.accentColor.copy(alpha = 0.6f),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontFamily = FontFamily.Monospace,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    modifier = Modifier
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .align(Alignment.TopEnd)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .padding(end = 3.dp, top = 2.dp),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Primary label
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                val label = when {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key.type == KeyType.CHARACTER && isUpperCase && key.shift.isNotEmpty() ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key.shift
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        key.type == KeyType.CHARACTER && isUpperCase ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        key.primary.uppercase()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else -> key.primary
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    val textColor = when (key.type) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                KeyType.ENTER          -> theme.accentColor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            KeyType.AI_TOOL        -> theme.accentColor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        KeyType.VOICE          -> theme.accentColor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    KeyType.CTRL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                KeyType.ALT_KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            KeyType.SUPER          -> Color(0xFF4499FF)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        KeyType.SHIFT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    KeyType.BACKSPACE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                KeyType.TAB,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            KeyType.ESC,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        KeyType.MODE_SWITCH,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    KeyType.SYMBOL_TOGGLE  -> theme.keyText.copy(alpha = 0.7f)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                KeyType.FN             -> Color(0xFF5555AA)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else                   -> theme.keyText
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            val fontSize = when (key.type) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        KeyType.CHARACTER -> if (label.length == 1) 15.sp else 10.sp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    KeyType.FN        -> 8.sp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                KeyType.SPACE     -> 9.sp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else              -> 9.sp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text       = label,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize   = fontSize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color      = textColor,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight = if (key.type == KeyType.CHARACTER) FontWeight.Medium else FontWeight.Normal,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontFamily = FontFamily.Monospace,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    maxLines   = 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }