package com.hackerboard.ui
 
 import androidx.compose.foundation.background
 import androidx.compose.foundation.clickable
 import androidx.compose.foundation.layout.*
 import androidx.compose.material3.Text
 import androidx.compose.runtime.Composable
 import androidx.compose.ui.Alignment
 import androidx.compose.ui.Modifier
 import androidx.compose.ui.text.font.FontFamily
 import androidx.compose.ui.unit.dp
 import androidx.compose.ui.unit.sp
 import com.hackerboard.themes.KeyboardTheme
  
  @Composable
  fun SuggestionBarUI(
      suggestions: List<String>,
          theme: KeyboardTheme,
              onSuggestion: (String) -> Unit,
              ) {
                  Row(
                          modifier = Modifier
                                      .fillMaxWidth()
                                                  .height(32.dp)
                                                              .background(theme.suggestionBg),
                                                                      verticalAlignment = Alignment.CenterVertically,
                                                                          ) {
                                                                                  suggestions.forEachIndexed { index, word ->
                                                                                              if (index > 0) {
                                                                                                              Box(
                                                                                                                                  modifier = Modifier
                                                                                                                                                          .width(1.dp)
                                                                                                                                                                                  .fillMaxHeight(0.6f)
                                                                                                                                                                                                          .background(theme.keyBorder),
                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                  Box(
                                                                                                                                                                                                                                                                  modifier = Modifier
                                                                                                                                                                                                                                                                                      .weight(1f)
                                                                                                                                                                                                                                                                                                          .fillMaxHeight()
                                                                                                                                                                                                                                                                                                                              .clickable { onSuggestion(word) },
                                                                                                                                                                                                                                                                                                                                              contentAlignment = Alignment.Center,
                                                                                                                                                                                                                                                                                                                                                          ) {
                                                                                                                                                                                                                                                                                                                                                                          Text(
                                                                                                                                                                                                                                                                                                                                                                                              text       = word,
                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize   = 12.sp,
                                                                                                                                                                                                                                                                                                                                                                                                                                      color      = theme.suggestionText,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontFamily = FontFamily.Monospace,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Fill remaining space if fewer than 3 suggestions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (suggestions.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Spacer(Modifier.fillMaxWidth())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }