package com.hackerboard.ui
 
 import androidx.compose.foundation.background
 import androidx.compose.foundation.border
 import androidx.compose.foundation.clickable
 import androidx.compose.foundation.horizontalScroll
 import androidx.compose.foundation.layout.*
 import androidx.compose.foundation.rememberScrollState
 import androidx.compose.foundation.shape.RoundedCornerShape
 import androidx.compose.material3.Text
 import androidx.compose.runtime.Composable
 import androidx.compose.ui.Alignment
 import androidx.compose.ui.Modifier
 import androidx.compose.ui.draw.clip
 import androidx.compose.ui.text.font.FontFamily
 import androidx.compose.ui.unit.dp
 import androidx.compose.ui.unit.sp
 import com.hackerboard.keyboard.PanelMode
 import com.hackerboard.themes.KeyboardTheme
  
  private data class ToolItem(val label: String, val mode: PanelMode)
   
   private val TOOLS = listOf(
       ToolItem("⌘ MACRO",  PanelMode.MACRO),
           ToolItem("{} SNIP",  PanelMode.SNIPPET),
               ToolItem("📋 CLIP",  PanelMode.CLIPBOARD),
                   ToolItem("⚙ HACKER", PanelMode.HACKER),
                       ToolItem("AI ✦",     PanelMode.AI),
                       )
                        
                        @Composable
                        fun ToolbarUI(
                            currentPanel: PanelMode,
                                theme: KeyboardTheme,
                                    onTool: (PanelMode) -> Unit,
                                    ) {
                                        Row(
                                                modifier = Modifier
                                                            .fillMaxWidth()
                                                                        .height(34.dp)
                                                                                    .background(theme.toolbarBg)
                                                                                                .horizontalScroll(rememberScrollState())
                                                                                                            .padding(horizontal = 6.dp),
                                                                                                                    verticalAlignment = Alignment.CenterVertically,
                                                                                                                            horizontalArrangement = Arrangement.spacedBy(6.dp),
                                                                                                                                ) {
                                                                                                                                        TOOLS.forEach { tool ->
                                                                                                                                                    val active = currentPanel == tool.mode
                                                                                                                                                                val shape  = RoundedCornerShape(6.dp)
                                                                                                                                                                            Box(
                                                                                                                                                                                            modifier = Modifier
                                                                                                                                                                                                                .clip(shape)
                                                                                                                                                                                                                                    .background(
                                                                                                                                                                                                                                                            if (active) theme.accentColor.copy(alpha = 0.12f)
                                                                                                                                                                                                                                                                                    else theme.keyBackground.copy(alpha = 0.6f)
                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                            .border(
                                                                                                                                                                                                                                                                                                                                                    0.5.dp,
                                                                                                                                                                                                                                                                                                                                                                            if (active) theme.accentColor.copy(alpha = 0.7f)
                                                                                                                                                                                                                                                                                                                                                                                                    else theme.keyBorder,
                                                                                                                                                                                                                                                                                                                                                                                                                            shape,
                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .clickable { onTool(tool.mode) }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .padding(horizontal = 10.dp, vertical = 4.dp),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        contentAlignment = Alignment.Center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text       = tool.label,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize   = 9.sp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color      = if (active) theme.accentColor else theme.suggestionText,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontFamily = FontFamily.Monospace,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        letterSpacing = 0.5.sp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }